# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dsc/ClionProjects/monero-gui

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dsc/ClionProjects/monero-gui

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dsc/ClionProjects/monero-gui/CMakeFiles /home/dsc/ClionProjects/monero-gui/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dsc/ClionProjects/monero-gui/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named obj_gui_version

# Build rule for target.
obj_gui_version: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_gui_version
.PHONY : obj_gui_version

# fast build rule for target.
obj_gui_version/fast:
	$(MAKE) -f CMakeFiles/obj_gui_version.dir/build.make CMakeFiles/obj_gui_version.dir/build
.PHONY : obj_gui_version/fast

#=============================================================================
# Target rules for targets named genversiongui

# Build rule for target.
genversiongui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 genversiongui
.PHONY : genversiongui

# fast build rule for target.
genversiongui/fast:
	$(MAKE) -f CMakeFiles/genversiongui.dir/build.make CMakeFiles/genversiongui.dir/build
.PHONY : genversiongui/fast

#=============================================================================
# Target rules for targets named gui_version

# Build rule for target.
gui_version: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gui_version
.PHONY : gui_version

# fast build rule for target.
gui_version/fast:
	$(MAKE) -f CMakeFiles/gui_version.dir/build.make CMakeFiles/gui_version.dir/build
.PHONY : gui_version/fast

#=============================================================================
# Target rules for targets named obj_gui_version_autogen

# Build rule for target.
obj_gui_version_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_gui_version_autogen
.PHONY : obj_gui_version_autogen

# fast build rule for target.
obj_gui_version_autogen/fast:
	$(MAKE) -f CMakeFiles/obj_gui_version_autogen.dir/build.make CMakeFiles/obj_gui_version_autogen.dir/build
.PHONY : obj_gui_version_autogen/fast

#=============================================================================
# Target rules for targets named gui_version_autogen

# Build rule for target.
gui_version_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gui_version_autogen
.PHONY : gui_version_autogen

# fast build rule for target.
gui_version_autogen/fast:
	$(MAKE) -f CMakeFiles/gui_version_autogen.dir/build.make CMakeFiles/gui_version_autogen.dir/build
.PHONY : gui_version_autogen/fast

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f monero/CMakeFiles/doc.dir/build.make monero/CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named generate_translations_header

# Build rule for target.
generate_translations_header: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generate_translations_header
.PHONY : generate_translations_header

# fast build rule for target.
generate_translations_header/fast:
	$(MAKE) -f monero/CMakeFiles/generate_translations_header.dir/build.make monero/CMakeFiles/generate_translations_header.dir/build
.PHONY : generate_translations_header/fast

#=============================================================================
# Target rules for targets named libminiupnpc-static

# Build rule for target.
libminiupnpc-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libminiupnpc-static
.PHONY : libminiupnpc-static

# fast build rule for target.
libminiupnpc-static/fast:
	$(MAKE) -f monero/external/miniupnp/miniupnpc/CMakeFiles/libminiupnpc-static.dir/build.make monero/external/miniupnp/miniupnpc/CMakeFiles/libminiupnpc-static.dir/build
.PHONY : libminiupnpc-static/fast

#=============================================================================
# Target rules for targets named lmdb

# Build rule for target.
lmdb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lmdb
.PHONY : lmdb

# fast build rule for target.
lmdb/fast:
	$(MAKE) -f monero/external/db_drivers/liblmdb/CMakeFiles/lmdb.dir/build.make monero/external/db_drivers/liblmdb/CMakeFiles/lmdb.dir/build
.PHONY : lmdb/fast

#=============================================================================
# Target rules for targets named easylogging

# Build rule for target.
easylogging: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 easylogging
.PHONY : easylogging

# fast build rule for target.
easylogging/fast:
	$(MAKE) -f monero/external/easylogging++/CMakeFiles/easylogging.dir/build.make monero/external/easylogging++/CMakeFiles/easylogging.dir/build
.PHONY : easylogging/fast

#=============================================================================
# Target rules for targets named randomx-tests

# Build rule for target.
randomx-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 randomx-tests
.PHONY : randomx-tests

# fast build rule for target.
randomx-tests/fast:
	$(MAKE) -f monero/external/randomx/CMakeFiles/randomx-tests.dir/build.make monero/external/randomx/CMakeFiles/randomx-tests.dir/build
.PHONY : randomx-tests/fast

#=============================================================================
# Target rules for targets named randomx

# Build rule for target.
randomx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 randomx
.PHONY : randomx

# fast build rule for target.
randomx/fast:
	$(MAKE) -f monero/external/randomx/CMakeFiles/randomx.dir/build.make monero/external/randomx/CMakeFiles/randomx.dir/build
.PHONY : randomx/fast

#=============================================================================
# Target rules for targets named randomx-codegen

# Build rule for target.
randomx-codegen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 randomx-codegen
.PHONY : randomx-codegen

# fast build rule for target.
randomx-codegen/fast:
	$(MAKE) -f monero/external/randomx/CMakeFiles/randomx-codegen.dir/build.make monero/external/randomx/CMakeFiles/randomx-codegen.dir/build
.PHONY : randomx-codegen/fast

#=============================================================================
# Target rules for targets named randomx-benchmark

# Build rule for target.
randomx-benchmark: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 randomx-benchmark
.PHONY : randomx-benchmark

# fast build rule for target.
randomx-benchmark/fast:
	$(MAKE) -f monero/external/randomx/CMakeFiles/randomx-benchmark.dir/build.make monero/external/randomx/CMakeFiles/randomx-benchmark.dir/build
.PHONY : randomx-benchmark/fast

#=============================================================================
# Target rules for targets named epee_readline

# Build rule for target.
epee_readline: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 epee_readline
.PHONY : epee_readline

# fast build rule for target.
epee_readline/fast:
	$(MAKE) -f monero/contrib/epee/src/CMakeFiles/epee_readline.dir/build.make monero/contrib/epee/src/CMakeFiles/epee_readline.dir/build
.PHONY : epee_readline/fast

#=============================================================================
# Target rules for targets named epee

# Build rule for target.
epee: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 epee
.PHONY : epee

# fast build rule for target.
epee/fast:
	$(MAKE) -f monero/contrib/epee/src/CMakeFiles/epee.dir/build.make monero/contrib/epee/src/CMakeFiles/epee.dir/build
.PHONY : epee/fast

#=============================================================================
# Target rules for targets named obj_version

# Build rule for target.
obj_version: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_version
.PHONY : obj_version

# fast build rule for target.
obj_version/fast:
	$(MAKE) -f monero/src/CMakeFiles/obj_version.dir/build.make monero/src/CMakeFiles/obj_version.dir/build
.PHONY : obj_version/fast

#=============================================================================
# Target rules for targets named genversion

# Build rule for target.
genversion: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 genversion
.PHONY : genversion

# fast build rule for target.
genversion/fast:
	$(MAKE) -f monero/src/CMakeFiles/genversion.dir/build.make monero/src/CMakeFiles/genversion.dir/build
.PHONY : genversion/fast

#=============================================================================
# Target rules for targets named version

# Build rule for target.
version: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 version
.PHONY : version

# fast build rule for target.
version/fast:
	$(MAKE) -f monero/src/CMakeFiles/version.dir/build.make monero/src/CMakeFiles/version.dir/build
.PHONY : version/fast

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) -f monero/src/common/CMakeFiles/common.dir/build.make monero/src/common/CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named obj_common

# Build rule for target.
obj_common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_common
.PHONY : obj_common

# fast build rule for target.
obj_common/fast:
	$(MAKE) -f monero/src/common/CMakeFiles/obj_common.dir/build.make monero/src/common/CMakeFiles/obj_common.dir/build
.PHONY : obj_common/fast

#=============================================================================
# Target rules for targets named obj_cncrypto

# Build rule for target.
obj_cncrypto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_cncrypto
.PHONY : obj_cncrypto

# fast build rule for target.
obj_cncrypto/fast:
	$(MAKE) -f monero/src/crypto/CMakeFiles/obj_cncrypto.dir/build.make monero/src/crypto/CMakeFiles/obj_cncrypto.dir/build
.PHONY : obj_cncrypto/fast

#=============================================================================
# Target rules for targets named cncrypto

# Build rule for target.
cncrypto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cncrypto
.PHONY : cncrypto

# fast build rule for target.
cncrypto/fast:
	$(MAKE) -f monero/src/crypto/CMakeFiles/cncrypto.dir/build.make monero/src/crypto/CMakeFiles/cncrypto.dir/build
.PHONY : cncrypto/fast

#=============================================================================
# Target rules for targets named ringct_basic

# Build rule for target.
ringct_basic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ringct_basic
.PHONY : ringct_basic

# fast build rule for target.
ringct_basic/fast:
	$(MAKE) -f monero/src/ringct/CMakeFiles/ringct_basic.dir/build.make monero/src/ringct/CMakeFiles/ringct_basic.dir/build
.PHONY : ringct_basic/fast

#=============================================================================
# Target rules for targets named obj_ringct_basic

# Build rule for target.
obj_ringct_basic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_ringct_basic
.PHONY : obj_ringct_basic

# fast build rule for target.
obj_ringct_basic/fast:
	$(MAKE) -f monero/src/ringct/CMakeFiles/obj_ringct_basic.dir/build.make monero/src/ringct/CMakeFiles/obj_ringct_basic.dir/build
.PHONY : obj_ringct_basic/fast

#=============================================================================
# Target rules for targets named obj_ringct

# Build rule for target.
obj_ringct: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_ringct
.PHONY : obj_ringct

# fast build rule for target.
obj_ringct/fast:
	$(MAKE) -f monero/src/ringct/CMakeFiles/obj_ringct.dir/build.make monero/src/ringct/CMakeFiles/obj_ringct.dir/build
.PHONY : obj_ringct/fast

#=============================================================================
# Target rules for targets named ringct

# Build rule for target.
ringct: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ringct
.PHONY : ringct

# fast build rule for target.
ringct/fast:
	$(MAKE) -f monero/src/ringct/CMakeFiles/ringct.dir/build.make monero/src/ringct/CMakeFiles/ringct.dir/build
.PHONY : ringct/fast

#=============================================================================
# Target rules for targets named checkpoints

# Build rule for target.
checkpoints: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 checkpoints
.PHONY : checkpoints

# fast build rule for target.
checkpoints/fast:
	$(MAKE) -f monero/src/checkpoints/CMakeFiles/checkpoints.dir/build.make monero/src/checkpoints/CMakeFiles/checkpoints.dir/build
.PHONY : checkpoints/fast

#=============================================================================
# Target rules for targets named obj_checkpoints

# Build rule for target.
obj_checkpoints: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_checkpoints
.PHONY : obj_checkpoints

# fast build rule for target.
obj_checkpoints/fast:
	$(MAKE) -f monero/src/checkpoints/CMakeFiles/obj_checkpoints.dir/build.make monero/src/checkpoints/CMakeFiles/obj_checkpoints.dir/build
.PHONY : obj_checkpoints/fast

#=============================================================================
# Target rules for targets named cryptonote_basic

# Build rule for target.
cryptonote_basic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cryptonote_basic
.PHONY : cryptonote_basic

# fast build rule for target.
cryptonote_basic/fast:
	$(MAKE) -f monero/src/cryptonote_basic/CMakeFiles/cryptonote_basic.dir/build.make monero/src/cryptonote_basic/CMakeFiles/cryptonote_basic.dir/build
.PHONY : cryptonote_basic/fast

#=============================================================================
# Target rules for targets named obj_cryptonote_basic

# Build rule for target.
obj_cryptonote_basic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_cryptonote_basic
.PHONY : obj_cryptonote_basic

# fast build rule for target.
obj_cryptonote_basic/fast:
	$(MAKE) -f monero/src/cryptonote_basic/CMakeFiles/obj_cryptonote_basic.dir/build.make monero/src/cryptonote_basic/CMakeFiles/obj_cryptonote_basic.dir/build
.PHONY : obj_cryptonote_basic/fast

#=============================================================================
# Target rules for targets named cryptonote_core

# Build rule for target.
cryptonote_core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cryptonote_core
.PHONY : cryptonote_core

# fast build rule for target.
cryptonote_core/fast:
	$(MAKE) -f monero/src/cryptonote_core/CMakeFiles/cryptonote_core.dir/build.make monero/src/cryptonote_core/CMakeFiles/cryptonote_core.dir/build
.PHONY : cryptonote_core/fast

#=============================================================================
# Target rules for targets named obj_cryptonote_core

# Build rule for target.
obj_cryptonote_core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_cryptonote_core
.PHONY : obj_cryptonote_core

# fast build rule for target.
obj_cryptonote_core/fast:
	$(MAKE) -f monero/src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/build.make monero/src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/build
.PHONY : obj_cryptonote_core/fast

#=============================================================================
# Target rules for targets named lmdb_lib

# Build rule for target.
lmdb_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lmdb_lib
.PHONY : lmdb_lib

# fast build rule for target.
lmdb_lib/fast:
	$(MAKE) -f monero/src/lmdb/CMakeFiles/lmdb_lib.dir/build.make monero/src/lmdb/CMakeFiles/lmdb_lib.dir/build
.PHONY : lmdb_lib/fast

#=============================================================================
# Target rules for targets named obj_lmdb_lib

# Build rule for target.
obj_lmdb_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_lmdb_lib
.PHONY : obj_lmdb_lib

# fast build rule for target.
obj_lmdb_lib/fast:
	$(MAKE) -f monero/src/lmdb/CMakeFiles/obj_lmdb_lib.dir/build.make monero/src/lmdb/CMakeFiles/obj_lmdb_lib.dir/build
.PHONY : obj_lmdb_lib/fast

#=============================================================================
# Target rules for targets named obj_multisig

# Build rule for target.
obj_multisig: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_multisig
.PHONY : obj_multisig

# fast build rule for target.
obj_multisig/fast:
	$(MAKE) -f monero/src/multisig/CMakeFiles/obj_multisig.dir/build.make monero/src/multisig/CMakeFiles/obj_multisig.dir/build
.PHONY : obj_multisig/fast

#=============================================================================
# Target rules for targets named multisig

# Build rule for target.
multisig: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 multisig
.PHONY : multisig

# fast build rule for target.
multisig/fast:
	$(MAKE) -f monero/src/multisig/CMakeFiles/multisig.dir/build.make monero/src/multisig/CMakeFiles/multisig.dir/build
.PHONY : multisig/fast

#=============================================================================
# Target rules for targets named net

# Build rule for target.
net: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 net
.PHONY : net

# fast build rule for target.
net/fast:
	$(MAKE) -f monero/src/net/CMakeFiles/net.dir/build.make monero/src/net/CMakeFiles/net.dir/build
.PHONY : net/fast

#=============================================================================
# Target rules for targets named obj_net

# Build rule for target.
obj_net: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_net
.PHONY : obj_net

# fast build rule for target.
obj_net/fast:
	$(MAKE) -f monero/src/net/CMakeFiles/obj_net.dir/build.make monero/src/net/CMakeFiles/obj_net.dir/build
.PHONY : obj_net/fast

#=============================================================================
# Target rules for targets named hardforks

# Build rule for target.
hardforks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hardforks
.PHONY : hardforks

# fast build rule for target.
hardforks/fast:
	$(MAKE) -f monero/src/hardforks/CMakeFiles/hardforks.dir/build.make monero/src/hardforks/CMakeFiles/hardforks.dir/build
.PHONY : hardforks/fast

#=============================================================================
# Target rules for targets named obj_hardforks

# Build rule for target.
obj_hardforks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_hardforks
.PHONY : obj_hardforks

# fast build rule for target.
obj_hardforks/fast:
	$(MAKE) -f monero/src/hardforks/CMakeFiles/obj_hardforks.dir/build.make monero/src/hardforks/CMakeFiles/obj_hardforks.dir/build
.PHONY : obj_hardforks/fast

#=============================================================================
# Target rules for targets named blockchain_db

# Build rule for target.
blockchain_db: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blockchain_db
.PHONY : blockchain_db

# fast build rule for target.
blockchain_db/fast:
	$(MAKE) -f monero/src/blockchain_db/CMakeFiles/blockchain_db.dir/build.make monero/src/blockchain_db/CMakeFiles/blockchain_db.dir/build
.PHONY : blockchain_db/fast

#=============================================================================
# Target rules for targets named obj_blockchain_db

# Build rule for target.
obj_blockchain_db: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_blockchain_db
.PHONY : obj_blockchain_db

# fast build rule for target.
obj_blockchain_db/fast:
	$(MAKE) -f monero/src/blockchain_db/CMakeFiles/obj_blockchain_db.dir/build.make monero/src/blockchain_db/CMakeFiles/obj_blockchain_db.dir/build
.PHONY : obj_blockchain_db/fast

#=============================================================================
# Target rules for targets named mnemonics

# Build rule for target.
mnemonics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mnemonics
.PHONY : mnemonics

# fast build rule for target.
mnemonics/fast:
	$(MAKE) -f monero/src/mnemonics/CMakeFiles/mnemonics.dir/build.make monero/src/mnemonics/CMakeFiles/mnemonics.dir/build
.PHONY : mnemonics/fast

#=============================================================================
# Target rules for targets named obj_mnemonics

# Build rule for target.
obj_mnemonics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_mnemonics
.PHONY : obj_mnemonics

# fast build rule for target.
obj_mnemonics/fast:
	$(MAKE) -f monero/src/mnemonics/CMakeFiles/obj_mnemonics.dir/build.make monero/src/mnemonics/CMakeFiles/obj_mnemonics.dir/build
.PHONY : obj_mnemonics/fast

#=============================================================================
# Target rules for targets named obj_daemon_messages

# Build rule for target.
obj_daemon_messages: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_daemon_messages
.PHONY : obj_daemon_messages

# fast build rule for target.
obj_daemon_messages/fast:
	$(MAKE) -f monero/src/rpc/CMakeFiles/obj_daemon_messages.dir/build.make monero/src/rpc/CMakeFiles/obj_daemon_messages.dir/build
.PHONY : obj_daemon_messages/fast

#=============================================================================
# Target rules for targets named rpc

# Build rule for target.
rpc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rpc
.PHONY : rpc

# fast build rule for target.
rpc/fast:
	$(MAKE) -f monero/src/rpc/CMakeFiles/rpc.dir/build.make monero/src/rpc/CMakeFiles/rpc.dir/build
.PHONY : rpc/fast

#=============================================================================
# Target rules for targets named obj_rpc

# Build rule for target.
obj_rpc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_rpc
.PHONY : obj_rpc

# fast build rule for target.
obj_rpc/fast:
	$(MAKE) -f monero/src/rpc/CMakeFiles/obj_rpc.dir/build.make monero/src/rpc/CMakeFiles/obj_rpc.dir/build
.PHONY : obj_rpc/fast

#=============================================================================
# Target rules for targets named obj_rpc_base

# Build rule for target.
obj_rpc_base: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_rpc_base
.PHONY : obj_rpc_base

# fast build rule for target.
obj_rpc_base/fast:
	$(MAKE) -f monero/src/rpc/CMakeFiles/obj_rpc_base.dir/build.make monero/src/rpc/CMakeFiles/obj_rpc_base.dir/build
.PHONY : obj_rpc_base/fast

#=============================================================================
# Target rules for targets named daemon_messages

# Build rule for target.
daemon_messages: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 daemon_messages
.PHONY : daemon_messages

# fast build rule for target.
daemon_messages/fast:
	$(MAKE) -f monero/src/rpc/CMakeFiles/daemon_messages.dir/build.make monero/src/rpc/CMakeFiles/daemon_messages.dir/build
.PHONY : daemon_messages/fast

#=============================================================================
# Target rules for targets named rpc_base

# Build rule for target.
rpc_base: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rpc_base
.PHONY : rpc_base

# fast build rule for target.
rpc_base/fast:
	$(MAKE) -f monero/src/rpc/CMakeFiles/rpc_base.dir/build.make monero/src/rpc/CMakeFiles/rpc_base.dir/build
.PHONY : rpc_base/fast

#=============================================================================
# Target rules for targets named obj_daemon_rpc_server

# Build rule for target.
obj_daemon_rpc_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_daemon_rpc_server
.PHONY : obj_daemon_rpc_server

# fast build rule for target.
obj_daemon_rpc_server/fast:
	$(MAKE) -f monero/src/rpc/CMakeFiles/obj_daemon_rpc_server.dir/build.make monero/src/rpc/CMakeFiles/obj_daemon_rpc_server.dir/build
.PHONY : obj_daemon_rpc_server/fast

#=============================================================================
# Target rules for targets named daemon_rpc_server

# Build rule for target.
daemon_rpc_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 daemon_rpc_server
.PHONY : daemon_rpc_server

# fast build rule for target.
daemon_rpc_server/fast:
	$(MAKE) -f monero/src/rpc/CMakeFiles/daemon_rpc_server.dir/build.make monero/src/rpc/CMakeFiles/daemon_rpc_server.dir/build
.PHONY : daemon_rpc_server/fast

#=============================================================================
# Target rules for targets named serialization

# Build rule for target.
serialization: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 serialization
.PHONY : serialization

# fast build rule for target.
serialization/fast:
	$(MAKE) -f monero/src/serialization/CMakeFiles/serialization.dir/build.make monero/src/serialization/CMakeFiles/serialization.dir/build
.PHONY : serialization/fast

#=============================================================================
# Target rules for targets named obj_serialization

# Build rule for target.
obj_serialization: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_serialization
.PHONY : obj_serialization

# fast build rule for target.
obj_serialization/fast:
	$(MAKE) -f monero/src/serialization/CMakeFiles/obj_serialization.dir/build.make monero/src/serialization/CMakeFiles/obj_serialization.dir/build
.PHONY : obj_serialization/fast

#=============================================================================
# Target rules for targets named wallet

# Build rule for target.
wallet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wallet
.PHONY : wallet

# fast build rule for target.
wallet/fast:
	$(MAKE) -f monero/src/wallet/CMakeFiles/wallet.dir/build.make monero/src/wallet/CMakeFiles/wallet.dir/build
.PHONY : wallet/fast

#=============================================================================
# Target rules for targets named obj_wallet

# Build rule for target.
obj_wallet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_wallet
.PHONY : obj_wallet

# fast build rule for target.
obj_wallet/fast:
	$(MAKE) -f monero/src/wallet/CMakeFiles/obj_wallet.dir/build.make monero/src/wallet/CMakeFiles/obj_wallet.dir/build
.PHONY : obj_wallet/fast

#=============================================================================
# Target rules for targets named wallet_rpc_server

# Build rule for target.
wallet_rpc_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wallet_rpc_server
.PHONY : wallet_rpc_server

# fast build rule for target.
wallet_rpc_server/fast:
	$(MAKE) -f monero/src/wallet/CMakeFiles/wallet_rpc_server.dir/build.make monero/src/wallet/CMakeFiles/wallet_rpc_server.dir/build
.PHONY : wallet_rpc_server/fast

#=============================================================================
# Target rules for targets named wallet_merged

# Build rule for target.
wallet_merged: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wallet_merged
.PHONY : wallet_merged

# fast build rule for target.
wallet_merged/fast:
	$(MAKE) -f monero/src/wallet/CMakeFiles/wallet_merged.dir/build.make monero/src/wallet/CMakeFiles/wallet_merged.dir/build
.PHONY : wallet_merged/fast

#=============================================================================
# Target rules for targets named wallet_api

# Build rule for target.
wallet_api: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wallet_api
.PHONY : wallet_api

# fast build rule for target.
wallet_api/fast:
	$(MAKE) -f monero/src/wallet/api/CMakeFiles/wallet_api.dir/build.make monero/src/wallet/api/CMakeFiles/wallet_api.dir/build
.PHONY : wallet_api/fast

#=============================================================================
# Target rules for targets named obj_wallet_api

# Build rule for target.
obj_wallet_api: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_wallet_api
.PHONY : obj_wallet_api

# fast build rule for target.
obj_wallet_api/fast:
	$(MAKE) -f monero/src/wallet/api/CMakeFiles/obj_wallet_api.dir/build.make monero/src/wallet/api/CMakeFiles/obj_wallet_api.dir/build
.PHONY : obj_wallet_api/fast

#=============================================================================
# Target rules for targets named p2p

# Build rule for target.
p2p: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p2p
.PHONY : p2p

# fast build rule for target.
p2p/fast:
	$(MAKE) -f monero/src/p2p/CMakeFiles/p2p.dir/build.make monero/src/p2p/CMakeFiles/p2p.dir/build
.PHONY : p2p/fast

#=============================================================================
# Target rules for targets named obj_p2p

# Build rule for target.
obj_p2p: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_p2p
.PHONY : obj_p2p

# fast build rule for target.
obj_p2p/fast:
	$(MAKE) -f monero/src/p2p/CMakeFiles/obj_p2p.dir/build.make monero/src/p2p/CMakeFiles/obj_p2p.dir/build
.PHONY : obj_p2p/fast

#=============================================================================
# Target rules for targets named cryptonote_protocol

# Build rule for target.
cryptonote_protocol: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cryptonote_protocol
.PHONY : cryptonote_protocol

# fast build rule for target.
cryptonote_protocol/fast:
	$(MAKE) -f monero/src/cryptonote_protocol/CMakeFiles/cryptonote_protocol.dir/build.make monero/src/cryptonote_protocol/CMakeFiles/cryptonote_protocol.dir/build
.PHONY : cryptonote_protocol/fast

#=============================================================================
# Target rules for targets named obj_cryptonote_protocol

# Build rule for target.
obj_cryptonote_protocol: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_cryptonote_protocol
.PHONY : obj_cryptonote_protocol

# fast build rule for target.
obj_cryptonote_protocol/fast:
	$(MAKE) -f monero/src/cryptonote_protocol/CMakeFiles/obj_cryptonote_protocol.dir/build.make monero/src/cryptonote_protocol/CMakeFiles/obj_cryptonote_protocol.dir/build
.PHONY : obj_cryptonote_protocol/fast

#=============================================================================
# Target rules for targets named simplewallet

# Build rule for target.
simplewallet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simplewallet
.PHONY : simplewallet

# fast build rule for target.
simplewallet/fast:
	$(MAKE) -f monero/src/simplewallet/CMakeFiles/simplewallet.dir/build.make monero/src/simplewallet/CMakeFiles/simplewallet.dir/build
.PHONY : simplewallet/fast

#=============================================================================
# Target rules for targets named gen_multisig

# Build rule for target.
gen_multisig: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gen_multisig
.PHONY : gen_multisig

# fast build rule for target.
gen_multisig/fast:
	$(MAKE) -f monero/src/gen_multisig/CMakeFiles/gen_multisig.dir/build.make monero/src/gen_multisig/CMakeFiles/gen_multisig.dir/build
.PHONY : gen_multisig/fast

#=============================================================================
# Target rules for targets named gen_ssl_cert

# Build rule for target.
gen_ssl_cert: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gen_ssl_cert
.PHONY : gen_ssl_cert

# fast build rule for target.
gen_ssl_cert/fast:
	$(MAKE) -f monero/src/gen_ssl_cert/CMakeFiles/gen_ssl_cert.dir/build.make monero/src/gen_ssl_cert/CMakeFiles/gen_ssl_cert.dir/build
.PHONY : gen_ssl_cert/fast

#=============================================================================
# Target rules for targets named daemonizer

# Build rule for target.
daemonizer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 daemonizer
.PHONY : daemonizer

# fast build rule for target.
daemonizer/fast:
	$(MAKE) -f monero/src/daemonizer/CMakeFiles/daemonizer.dir/build.make monero/src/daemonizer/CMakeFiles/daemonizer.dir/build
.PHONY : daemonizer/fast

#=============================================================================
# Target rules for targets named obj_daemonizer

# Build rule for target.
obj_daemonizer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_daemonizer
.PHONY : obj_daemonizer

# fast build rule for target.
obj_daemonizer/fast:
	$(MAKE) -f monero/src/daemonizer/CMakeFiles/obj_daemonizer.dir/build.make monero/src/daemonizer/CMakeFiles/obj_daemonizer.dir/build
.PHONY : obj_daemonizer/fast

#=============================================================================
# Target rules for targets named daemon

# Build rule for target.
daemon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 daemon
.PHONY : daemon

# fast build rule for target.
daemon/fast:
	$(MAKE) -f monero/src/daemon/CMakeFiles/daemon.dir/build.make monero/src/daemon/CMakeFiles/daemon.dir/build
.PHONY : daemon/fast

#=============================================================================
# Target rules for targets named blockchain_usage

# Build rule for target.
blockchain_usage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blockchain_usage
.PHONY : blockchain_usage

# fast build rule for target.
blockchain_usage/fast:
	$(MAKE) -f monero/src/blockchain_utilities/CMakeFiles/blockchain_usage.dir/build.make monero/src/blockchain_utilities/CMakeFiles/blockchain_usage.dir/build
.PHONY : blockchain_usage/fast

#=============================================================================
# Target rules for targets named blockchain_blackball

# Build rule for target.
blockchain_blackball: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blockchain_blackball
.PHONY : blockchain_blackball

# fast build rule for target.
blockchain_blackball/fast:
	$(MAKE) -f monero/src/blockchain_utilities/CMakeFiles/blockchain_blackball.dir/build.make monero/src/blockchain_utilities/CMakeFiles/blockchain_blackball.dir/build
.PHONY : blockchain_blackball/fast

#=============================================================================
# Target rules for targets named blockchain_ancestry

# Build rule for target.
blockchain_ancestry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blockchain_ancestry
.PHONY : blockchain_ancestry

# fast build rule for target.
blockchain_ancestry/fast:
	$(MAKE) -f monero/src/blockchain_utilities/CMakeFiles/blockchain_ancestry.dir/build.make monero/src/blockchain_utilities/CMakeFiles/blockchain_ancestry.dir/build
.PHONY : blockchain_ancestry/fast

#=============================================================================
# Target rules for targets named blockchain_stats

# Build rule for target.
blockchain_stats: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blockchain_stats
.PHONY : blockchain_stats

# fast build rule for target.
blockchain_stats/fast:
	$(MAKE) -f monero/src/blockchain_utilities/CMakeFiles/blockchain_stats.dir/build.make monero/src/blockchain_utilities/CMakeFiles/blockchain_stats.dir/build
.PHONY : blockchain_stats/fast

#=============================================================================
# Target rules for targets named blockchain_export

# Build rule for target.
blockchain_export: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blockchain_export
.PHONY : blockchain_export

# fast build rule for target.
blockchain_export/fast:
	$(MAKE) -f monero/src/blockchain_utilities/CMakeFiles/blockchain_export.dir/build.make monero/src/blockchain_utilities/CMakeFiles/blockchain_export.dir/build
.PHONY : blockchain_export/fast

#=============================================================================
# Target rules for targets named blockchain_depth

# Build rule for target.
blockchain_depth: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blockchain_depth
.PHONY : blockchain_depth

# fast build rule for target.
blockchain_depth/fast:
	$(MAKE) -f monero/src/blockchain_utilities/CMakeFiles/blockchain_depth.dir/build.make monero/src/blockchain_utilities/CMakeFiles/blockchain_depth.dir/build
.PHONY : blockchain_depth/fast

#=============================================================================
# Target rules for targets named blockchain_prune_known_spent_data

# Build rule for target.
blockchain_prune_known_spent_data: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blockchain_prune_known_spent_data
.PHONY : blockchain_prune_known_spent_data

# fast build rule for target.
blockchain_prune_known_spent_data/fast:
	$(MAKE) -f monero/src/blockchain_utilities/CMakeFiles/blockchain_prune_known_spent_data.dir/build.make monero/src/blockchain_utilities/CMakeFiles/blockchain_prune_known_spent_data.dir/build
.PHONY : blockchain_prune_known_spent_data/fast

#=============================================================================
# Target rules for targets named blockchain_import

# Build rule for target.
blockchain_import: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blockchain_import
.PHONY : blockchain_import

# fast build rule for target.
blockchain_import/fast:
	$(MAKE) -f monero/src/blockchain_utilities/CMakeFiles/blockchain_import.dir/build.make monero/src/blockchain_utilities/CMakeFiles/blockchain_import.dir/build
.PHONY : blockchain_import/fast

#=============================================================================
# Target rules for targets named blockchain_prune

# Build rule for target.
blockchain_prune: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blockchain_prune
.PHONY : blockchain_prune

# fast build rule for target.
blockchain_prune/fast:
	$(MAKE) -f monero/src/blockchain_utilities/CMakeFiles/blockchain_prune.dir/build.make monero/src/blockchain_utilities/CMakeFiles/blockchain_prune.dir/build
.PHONY : blockchain_prune/fast

#=============================================================================
# Target rules for targets named blocks

# Build rule for target.
blocks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blocks
.PHONY : blocks

# fast build rule for target.
blocks/fast:
	$(MAKE) -f monero/src/blocks/CMakeFiles/blocks.dir/build.make monero/src/blocks/CMakeFiles/blocks.dir/build
.PHONY : blocks/fast

#=============================================================================
# Target rules for targets named device

# Build rule for target.
device: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 device
.PHONY : device

# fast build rule for target.
device/fast:
	$(MAKE) -f monero/src/device/CMakeFiles/device.dir/build.make monero/src/device/CMakeFiles/device.dir/build
.PHONY : device/fast

#=============================================================================
# Target rules for targets named obj_device

# Build rule for target.
obj_device: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_device
.PHONY : obj_device

# fast build rule for target.
obj_device/fast:
	$(MAKE) -f monero/src/device/CMakeFiles/obj_device.dir/build.make monero/src/device/CMakeFiles/obj_device.dir/build
.PHONY : obj_device/fast

#=============================================================================
# Target rules for targets named obj_device_trezor

# Build rule for target.
obj_device_trezor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_device_trezor
.PHONY : obj_device_trezor

# fast build rule for target.
obj_device_trezor/fast:
	$(MAKE) -f monero/src/device_trezor/CMakeFiles/obj_device_trezor.dir/build.make monero/src/device_trezor/CMakeFiles/obj_device_trezor.dir/build
.PHONY : obj_device_trezor/fast

#=============================================================================
# Target rules for targets named device_trezor

# Build rule for target.
device_trezor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 device_trezor
.PHONY : device_trezor

# fast build rule for target.
device_trezor/fast:
	$(MAKE) -f monero/src/device_trezor/CMakeFiles/device_trezor.dir/build.make monero/src/device_trezor/CMakeFiles/device_trezor.dir/build
.PHONY : device_trezor/fast

#=============================================================================
# Target rules for targets named monero-wallet-gui

# Build rule for target.
monero-wallet-gui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 monero-wallet-gui
.PHONY : monero-wallet-gui

# fast build rule for target.
monero-wallet-gui/fast:
	$(MAKE) -f src/CMakeFiles/monero-wallet-gui.dir/build.make src/CMakeFiles/monero-wallet-gui.dir/build
.PHONY : monero-wallet-gui/fast

#=============================================================================
# Target rules for targets named monero-wallet-gui_autogen

# Build rule for target.
monero-wallet-gui_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 monero-wallet-gui_autogen
.PHONY : monero-wallet-gui_autogen

# fast build rule for target.
monero-wallet-gui_autogen/fast:
	$(MAKE) -f src/CMakeFiles/monero-wallet-gui_autogen.dir/build.make src/CMakeFiles/monero-wallet-gui_autogen.dir/build
.PHONY : monero-wallet-gui_autogen/fast

#=============================================================================
# Target rules for targets named openpgp

# Build rule for target.
openpgp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openpgp
.PHONY : openpgp

# fast build rule for target.
openpgp/fast:
	$(MAKE) -f src/openpgp/CMakeFiles/openpgp.dir/build.make src/openpgp/CMakeFiles/openpgp.dir/build
.PHONY : openpgp/fast

#=============================================================================
# Target rules for targets named openpgp_autogen

# Build rule for target.
openpgp_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openpgp_autogen
.PHONY : openpgp_autogen

# fast build rule for target.
openpgp_autogen/fast:
	$(MAKE) -f src/openpgp/CMakeFiles/openpgp_autogen.dir/build.make src/openpgp/CMakeFiles/openpgp_autogen.dir/build
.PHONY : openpgp_autogen/fast

gui_version_autogen/mocs_compilation.o: gui_version_autogen/mocs_compilation.cpp.o

.PHONY : gui_version_autogen/mocs_compilation.o

# target to build an object file
gui_version_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/gui_version.dir/build.make CMakeFiles/gui_version.dir/gui_version_autogen/mocs_compilation.cpp.o
.PHONY : gui_version_autogen/mocs_compilation.cpp.o

gui_version_autogen/mocs_compilation.i: gui_version_autogen/mocs_compilation.cpp.i

.PHONY : gui_version_autogen/mocs_compilation.i

# target to preprocess a source file
gui_version_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/gui_version.dir/build.make CMakeFiles/gui_version.dir/gui_version_autogen/mocs_compilation.cpp.i
.PHONY : gui_version_autogen/mocs_compilation.cpp.i

gui_version_autogen/mocs_compilation.s: gui_version_autogen/mocs_compilation.cpp.s

.PHONY : gui_version_autogen/mocs_compilation.s

# target to generate assembly for a file
gui_version_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/gui_version.dir/build.make CMakeFiles/gui_version.dir/gui_version_autogen/mocs_compilation.cpp.s
.PHONY : gui_version_autogen/mocs_compilation.cpp.s

obj_gui_version_autogen/mocs_compilation.o: obj_gui_version_autogen/mocs_compilation.cpp.o

.PHONY : obj_gui_version_autogen/mocs_compilation.o

# target to build an object file
obj_gui_version_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/obj_gui_version.dir/build.make CMakeFiles/obj_gui_version.dir/obj_gui_version_autogen/mocs_compilation.cpp.o
.PHONY : obj_gui_version_autogen/mocs_compilation.cpp.o

obj_gui_version_autogen/mocs_compilation.i: obj_gui_version_autogen/mocs_compilation.cpp.i

.PHONY : obj_gui_version_autogen/mocs_compilation.i

# target to preprocess a source file
obj_gui_version_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/obj_gui_version.dir/build.make CMakeFiles/obj_gui_version.dir/obj_gui_version_autogen/mocs_compilation.cpp.i
.PHONY : obj_gui_version_autogen/mocs_compilation.cpp.i

obj_gui_version_autogen/mocs_compilation.s: obj_gui_version_autogen/mocs_compilation.cpp.s

.PHONY : obj_gui_version_autogen/mocs_compilation.s

# target to generate assembly for a file
obj_gui_version_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/obj_gui_version.dir/build.make CMakeFiles/obj_gui_version.dir/obj_gui_version_autogen/mocs_compilation.cpp.s
.PHONY : obj_gui_version_autogen/mocs_compilation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... obj_gui_version"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... genversiongui"
	@echo "... gui_version"
	@echo "... edit_cache"
	@echo "... obj_gui_version_autogen"
	@echo "... gui_version_autogen"
	@echo "... doc"
	@echo "... generate_translations_header"
	@echo "... libminiupnpc-static"
	@echo "... lmdb"
	@echo "... easylogging"
	@echo "... randomx-tests"
	@echo "... randomx"
	@echo "... randomx-codegen"
	@echo "... randomx-benchmark"
	@echo "... epee_readline"
	@echo "... epee"
	@echo "... obj_version"
	@echo "... genversion"
	@echo "... version"
	@echo "... common"
	@echo "... obj_common"
	@echo "... obj_cncrypto"
	@echo "... cncrypto"
	@echo "... ringct_basic"
	@echo "... obj_ringct_basic"
	@echo "... obj_ringct"
	@echo "... ringct"
	@echo "... checkpoints"
	@echo "... obj_checkpoints"
	@echo "... cryptonote_basic"
	@echo "... obj_cryptonote_basic"
	@echo "... cryptonote_core"
	@echo "... obj_cryptonote_core"
	@echo "... lmdb_lib"
	@echo "... obj_lmdb_lib"
	@echo "... obj_multisig"
	@echo "... multisig"
	@echo "... net"
	@echo "... obj_net"
	@echo "... hardforks"
	@echo "... obj_hardforks"
	@echo "... blockchain_db"
	@echo "... obj_blockchain_db"
	@echo "... mnemonics"
	@echo "... obj_mnemonics"
	@echo "... obj_daemon_messages"
	@echo "... rpc"
	@echo "... obj_rpc"
	@echo "... obj_rpc_base"
	@echo "... daemon_messages"
	@echo "... rpc_base"
	@echo "... obj_daemon_rpc_server"
	@echo "... daemon_rpc_server"
	@echo "... serialization"
	@echo "... obj_serialization"
	@echo "... wallet"
	@echo "... obj_wallet"
	@echo "... wallet_rpc_server"
	@echo "... wallet_merged"
	@echo "... wallet_api"
	@echo "... obj_wallet_api"
	@echo "... p2p"
	@echo "... obj_p2p"
	@echo "... cryptonote_protocol"
	@echo "... obj_cryptonote_protocol"
	@echo "... simplewallet"
	@echo "... gen_multisig"
	@echo "... gen_ssl_cert"
	@echo "... daemonizer"
	@echo "... obj_daemonizer"
	@echo "... daemon"
	@echo "... blockchain_usage"
	@echo "... blockchain_blackball"
	@echo "... blockchain_ancestry"
	@echo "... blockchain_stats"
	@echo "... blockchain_export"
	@echo "... blockchain_depth"
	@echo "... blockchain_prune_known_spent_data"
	@echo "... blockchain_import"
	@echo "... blockchain_prune"
	@echo "... blocks"
	@echo "... device"
	@echo "... obj_device"
	@echo "... obj_device_trezor"
	@echo "... device_trezor"
	@echo "... monero-wallet-gui"
	@echo "... monero-wallet-gui_autogen"
	@echo "... openpgp"
	@echo "... openpgp_autogen"
	@echo "... gui_version_autogen/mocs_compilation.o"
	@echo "... gui_version_autogen/mocs_compilation.i"
	@echo "... gui_version_autogen/mocs_compilation.s"
	@echo "... obj_gui_version_autogen/mocs_compilation.o"
	@echo "... obj_gui_version_autogen/mocs_compilation.i"
	@echo "... obj_gui_version_autogen/mocs_compilation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

