name: Dinastycoin Linux Build

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Autorizza la creazione della Release
    
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Costruzione Immagine e AppImage (Docker)
        run: |
          # Avvia il Dockerfile (compilazione + OpenGL fix + AppImage)
          docker build --tag dinasty-build --file Dockerfile.linux .

      - name: Estrai AppImage e genera Checksum
        run: |
          # Pescaggio del file dal container e creazione SHA256
          docker create --name temp-container dinasty-build
          docker cp temp-container:/dinastycoin-gui/Dinastycoin_Wallet_GUI-x86_64.AppImage ./Dinastycoin_Wallet_GUI-x86_64.AppImage
          docker rm temp-container
          sha256sum Dinastycoin_Wallet_GUI-x86_64.AppImage > Dinastycoin_Wallet_GUI-x86_64.AppImage.sha256

      - name: Crea Tag con data
        id: tagger
        run: |
          TAG_NAME="build-$(date +'%Y.%m.%d-%H%M')"
          echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Pubblica Release Ufficiale
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tagger.outputs.tag }}
          name: Dinastycoin Wallet GUI - ${{ steps.tagger.outputs.tag }}
          draft: false
          prerelease: false
          files: |
            ./Dinastycoin_Wallet_GUI-x86_64.AppImage
            ./Dinastycoin_Wallet_GUI-x86_64.AppImage.sha256
