name: ci/gh-actions/verify
on: 
  push:
    paths:
      - 'src/p2pool/P2PoolManager.cpp'
  pull_request:
    paths:
      - 'src/p2pool/P2PoolManager.cpp'
jobs:
  p2pool-hashes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Verify Hashes
      run: |
        python3 .github/verify_p2pool.py
